### ISSUE TITLE
Migrate lessons and issues from dme26

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#1]
Thanks @ErinBecker for setting up this repo!

@dme26 I think first thing we need to:
- [x] Migrate the episodes to this new repo
- [x] Migrate the issues to this new repo
- [x] Update the readme 
- [x] Homepage introduction

from https://github.com/dme26/docker-introduction

Let me know if there other other first things we need to do

**Comment by dme26** [comment]
Yes, that looks ideal, and thanks for already doing the episode migration! I'll have a think about how to best change the dme26 repository to point over here, too.

**Comment by sstevens2** [comment]
We could leave a redirect repo?  Example [here](https://github.com/UW-Madison-DataScience/uw-madison-datascience.github.io).  Redirects our github io to our main webpage.

**Comment by sstevens2** [comment]
I'm struggling with how to migrate issues.  There is a transfer issue button but I'm not sure you can transfer them between organizations/users.

**Comment by ErinBecker** [comment]
Ah, good point. I think you're right about only being able to transfer issues within an organization. We can transfer ownership of your original repo to this org, then transfer the issues, and then transfer ownership of the repo back to your user. Not an elegant solution, but should work. I'll give you permission to transfer/create new repos. Let me know if you need any help.

**Comment by ErinBecker** [comment]
You should have the right permissions now.

**Comment by sstevens2** [comment]
@dme26 I think you will have to do this one.  I don't currently have the permissions to access the settings for the [original repo](https://github.com/dme26/docker-introduction).

**Comment by ErinBecker** [comment]
@dme26 - you also have member access to the incubators GH org so should be able to do this transfer. Please let me know if you run into any trouble.

**Comment by dme26** [comment]
Finally some progress on this from me, and my apologies for the delay. (Current super-focused undergraduate teaching spike. Great fun, but nearly all consuming. Diminishing over the next four weeks...)

**Comment by dme26** [comment]
I think transferring issues can only be done either between the same user's repositories, or within an organisation's repositories if you're an owner. I'm not an owner of the carpentries-incubator, and shouldn't be, and dme26/docker-introduction is a user repository. So I:
- created a new repository docker-issue-transfer in dme26
- transferred the relevant issues from docker-introduction to docker-issue-transfer within dme26
- transferred ownership of the docker-issue-transfer _repository_ to the organisation dme-test-org
- added @ErinBecker as an owner of dme-test-org

So hopefully now, @ErinBecker will be able to:

- transfer ownership of the docker-issue-transfer repository to organisation carpentries-incubator
- transfer issues from docker-issue-transfer to docker-introduction
- delete repository docker-issue-transfer

Easy! 😉 

(I also spammed @ErinBecker with a pointless dme26 repository invite—apologies!—and actually had a few more broken pre-steps above by first trying to create docker-issue-transfer in dme-test-org, assuming I'd be able to transfer issues to it from dme26, which isn't permitted.)

**Comment by ErinBecker** [comment]
Thanks for the work on this @dme26 and for the step-by-step instructions! Really helpful! I've finished transferring over the issues and have deleted the docker-issue-transfer repo. I won't close this issue because I see that @sstevens2 has a few other checklist items in the original issue. Thanks both!

**Comment by sstevens2** [comment]
I think all the transfers over are complete so I'll go ahead and close this issue.  @dme26 feel free to re-open or make a new issue if you notice anything missing.
