### ISSUE TITLE
Follow best practices for building images - taking advantage of the cache.

### ISSUE THREAD

**Issue by MiddelkoopT** [carpentries-incubator/docker-introduction#125]
In [05b-advanced-containers](https://github.com/carpentries-incubator/docker-introduction/blob/gh-pages/_episodes/05b-managing-containers.md) in the section "Add the sum.py script to the PATH so you can run it directly:"
```
FROM alpine

COPY sum.py /home
# set script permissions
RUN chmod +x /home/sum.py
# add /home folder to the PATH
ENV PATH /home:$PATH

RUN apk add --update python3 py3-pip python3-dev
```

Should look something like
```
FROM alpine

RUN apk add --update python3 py3-pip python3-dev

COPY sum.py /home
# set script permissions
RUN chmod +x /home/sum.py
# add /home folder to the PATH
ENV PATH /home:$PATH
```

With the heavy download first (`RUN apk add`) to take advantage of the cache layers.

I can do a PR for this if desired.

**Comment by jcohen02** [comment]
Thanks @MiddelkoopT, just running through some outstanding issues and have opened a PR for this.
