### ISSUE TITLE
Include "10 Simple Rules for Dockerfiles" reference

### ISSUE THREAD

**Issue by sgibson91** [carpentries-incubator/docker-introduction#128]
Hi all, thanks very much for developing this lesson! I'm keen to help teach it at some point

I'm dropping a link to an article "10 Simple Rules for writing Dockerfiles for reproducible data science" that I think would be an excellent additional reference for this lesson https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008316

**Comment by svenvanderburg** [comment]
That paper comes with a github repo that has really nice real-world examples of docker images: https://github.com/nuest/ten-simple-rules-dockerfiles/tree/master/examples .

**Comment by jcohen02** [comment]
Thanks for the suggestion @sgibson91, and the link to the examples @svenvanderburg. It's a shame that not all the examples are working at present but really good to highlight that section of the repository nonetheless.

I wasn't sure of the best place to add this information so for now I've just added a small callout box to the end of the [advanced containers epsiode (05b)](https://github.com/carpentries-incubator/docker-introduction/blob/gh-pages/_episodes/05b-advanced-containers.md). It seems reasonable to highlight this once all the information about `Dockerfile`s has been covered. However, I also thought it may fit a little earlier on where the initial `Dockerfile` overview is provided in the main episode 5 content.

Feel free to suggest edits/additions to the text in PR #139, or to suggest moving the material to an alternative location.
