### ISSUE TITLE
Planning upcoming lesson development sprint - Sept/Oct 2021

### ISSUE THREAD

**Issue by jcohen02** [carpentries-incubator/docker-introduction#135]
------
The next _docker-introduction_ lesson sprint is confirmed for **Tuesday 5th October 2021**.

The core lesson maintainer team includes participants based in New Zealand, the UK and the US. The proposed co-working time slots are as follows:

| Sprint session | Time (UTC) | Time (US-CDT) | Time (UK) | Time (NZ) | Description |
|----------------|-------------|-----------|-----------|-----------------|------------|
| Sprint 1 | **07:00 - 10:00** | | 08:00-11:00 | 20:00-23:00 | Co-work UK (NZ optional) |
| Sprint 2 | **13:00 - 16:00** | 08:00-11:00 | 14:00-17:00 |   | Co-work UK / US |
| Break | **16:00 - 17:00** |  |  |  |  |
| Sprint 3 | **17:00 - 20:00** | 12:00-15:00 | 18:00-21:00 |   | Co-work US (UK optional) |
| Break | **20:00 - 21:00** |  |  |  |  |
| Sprint 4 | **21:00 - 24:00** | 16:00-19:00 | 22:00-01:00 | 10:00-13:00 <br/>(6th Oct)  | Co-work US (UK/NZ optional) |

Anyone interested to contribute to the lesson material is welcome to join any of the above sprint sessions. You can let us know in this issue if you're planning to join, or contact @jcohen02, @sstevens2 or @ChristinaLK for join details.

------

Hi everyone,

Following our very successful lesson development sprint back in early June (see #94), where we went through the lesson material and made a number of decisions about the future direction of the content and also undertook a series of development sprints working on the content, it's been proposed that we have a follow up sprint. The plan is for this to take place in September/October 2021 over a full day, split into a series of sessions to suit different groups of timezones, as we did with the previous sprint.

I'm proposing a set of possible dates below - @carpentries-incubator/docker-introduction-maintainers please vote for your preferred date(s). Anyone is welcome to join the sprint so if you're interested to get involved with the lesson, you're welcome to also vote for your preferred date(s). I'm happy to provide some further dates into October if none of these are practical...

 - Thursday 23rd September (🎉)
 - Thursday 30th September (👍)
 - Tuesday 5th October (🚀)
 - Wednesday 6th October (😄)
 - Thursday 7th October (👀)
 - None of the above (👎)

**Comment by dme26** [comment]
(That's spanning the last few weeks of semester for me, so I'm likely to have interruptions on any of the above dates, but they're not impossible, either.)

**Comment by sstevens2** [comment]
Replied with my options.  I really can't do Sept 23rd because I'm teaching instructor training.  I'd also prefer not Oct 7th because I'd have to reschedule a lot of meetings.

**Comment by jcohen02** [comment]
Thanks for adding your availability and sorry the timing is not great @dme26. It's looking like Tuesday 5th October could be a reasonable date to go with so I'm going to suggest we pencil that in and I'll update with further details here in due course, assuming nothing comes up and we're all still OK with this. However, if you feel pushing this back to later in October would be preferable, let me know.

**Comment by ChristinaLK** [comment]
Tuesday the 5th works for me; I'll have to miss 2 hours for office hours but otherwise I can block it off now.

**Comment by sstevens2** [comment]
Blocked on my calendar too.

**Comment by mmalenta** [comment]
Hello, I will joining for Sprints 1 and 2 (possibly 3).
