### ISSUE TITLE
hackotberfest 

### ISSUE THREAD

**Issue by fmichonneau** [carpentries-incubator/docker-introduction#140]
hello Maintainers,

Your repository currently has the "hacktoberfest" tag which means that people will be able to make contributions to it to count towards their challenge (see [the Hacktoberfest website](https://hacktoberfest.digitalocean.com) for more info).

While the event is great to encourage people to contribute to open-source projects, in recent years, we have seen that there is sometimes an influx of low-quality pull requests on such repositories as people try to get their 4 pull requests with trivial changes. You will be able to mark these pull requests with the label "spam" or "invalid" so these PR won't count.

Alternatively, you can use an "opt-in" model where you don't need to have the "hacktoberfest" topic on your repository, and you can tag pull requests that are high-quality with the "hacktoberfest-accepted" label.

Let me know if you have any questions.

**Comment by sstevens2** [comment]
Thanks @fmichonneau.  We didn't get much spam last year but will watch out for it.
