### ISSUE TITLE
Carefully Proof Episodes for Container/Image usage

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#142]
Noticed that the format in the [Docker Hub Episode](https://github.com/carpentries-incubator/docker-introduction/edit/gh-pages/_episodes/04-docker-hub.md) is..

```
OWNER/CONTAINERNAME:TAG
```
Where I feel like to be consistent about how we use image vs container it should be
```
OWNER/IMAGENAME:TAG
```

This lead me to read this page critically and I noticed a lot of the use of the word "containers" very generally when perhaps we should be saying "container images" to help reinforce the difference between a running container instance and a container image.

Maybe something to work on at next week's sprint?

**Comment by sstevens2** [comment]
Then again yesterday I struggled to call running containers by the right term.  I accidentally say image a lot.

**Comment by jcohen02** [comment]
I think you're quite correct in saying that text in the episode should say:

```
OWNER/IMAGENAME:TAG
```

I probably need to check this more carefully in case I'm missing the context but I think this is an error. There are also a few instances of other text saying things like:

```
But if I wanted to download a Python 3.6 container, I would use this name:
```

I think to be consistent with the way we explain things earlier in the lesson, this should probably say something like:

```
But if I wanted to download a Python 3.6 image and run a container from it, I would use this name:
```

I agree that this terminology is very easy to make a mistake with, I've certainly found that when teaching the Singularity material, and in the above example, the language is possibly starting to get a bit less clear - as you say, something useful to discuss in the sprint.

**Comment by sstevens2** [comment]
From the 2021-10-05 Docker sprint: we suggest this issue be proofing all episodes, not only the ones mentioned in the original issue.

**Comment by ChristinaLK** [comment]
There was definitely an old issue about this (#20) that had to be closed because it got hijacked for another discussion, so glad to see this re-opened.
