### ISSUE TITLE
Swap Finding Containers and Removing Containers

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#147]
Suggestion at 2021-10-05 spring to swap finding containers on docker hub episode and cleaning up containers episode.

@jcohen02 and @sstevens2 think it works in either order.  Additional opinions welcome!

**Comment by sstevens2** [comment]
Note we might want to stop using numbering to order and then use order in the `_config.yml` file.  This change will create conflicts in all PRs that exist at that time, so we might want to wait on it.

**Comment by ChristinaLK** [comment]
no strong feelings from me either. I guess if you swap, then the flow would be: 
- download, run, clean
- find or make

I'd be in favor of not numbering any more. 😁

**Comment by aturner-epcc** [comment]
This has been done
