### ISSUE TITLE
Add instructor notes

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/docker-introduction#17]
Windows troubleshooting advice? 

Which parts of the lesson to skip / emphasize.

**Comment by sstevens2** [comment]
If I recall and issue we had with windows was getting people to install the right docker setup.  It differed between Windows Home and Pro.  This maybe have been improved since last year.  Maybe we should check the setup and test install on a few windows machines?

**Comment by dme26** [comment]
That would be ideal! I don't believe that I have easy access to Windows 10 Home Edition machines... (or indeed any Windows machines...)

My recollection of the Windows 10 Home problem was that that OS variant lacked hypervisor features that Docker Desktop needed, but from the look of https://docs.docker.com/docker-for-windows/install-windows-home/ it seems that WSL 2 has now provided a different route forward.

**Comment by sstevens2** [comment]
I'm realizing now that Christina meant this issue to be a list of things to add to instructor notes.  I'm still thinking we should test the windows install on windows computers and maybe update the install directions as needed.  Perhaps this is actually issue #3 instead?

**Comment by sstevens2** [comment]
Sorry accidental close

**Comment by jcohen02** [comment]
As an extension to the initial content for the instructor notes in #55, I think the following could be useful additions:

- Advice to address confusion from Linux users (does this affect macOS users too?) about when and why to use `sudo` when running docker commands
- Advice about file ownership, especially in files created in bind mounted directories - although actually it looks like this might now be much less of an issue from recent experience.

**Comment by sstevens2** [comment]
@jcohen02 I think those are both great additions!  I'm feeling like they might be good to have inline in the lessons as callouts near the topics in question.  I'm not sure where the callout for `sudo` would go but the file ownership one could be in a callout near mounting a volume section would be great!
