### ISSUE TITLE
Ep: Advanced containers  'Types of mounts' callout box has no formatting

### ISSUE THREAD

**Issue by gcapes** [carpentries-incubator/docker-introduction#180]
This is missing the `{: .callout}`  identifier so it just renders as a quote:

![image](https://user-images.githubusercontent.com/12446270/155144848-8d5776fd-1fec-4a90-8376-a1de6a7b3833.png)

**Comment by jcohen02** [comment]
Many thanks @gcapes, fixed in #181.
