### ISSUE TITLE
Ep: Advanced Containers - missing step in Dockerfile prep

### ISSUE THREAD

**Issue by gcapes** [carpentries-incubator/docker-introduction#182]
[At this point](https://carpentries-incubator.github.io/docker-introduction/advanced-containers/index.html#including-your-scripts-and-data-within-a-container-image) learners are supposed to edit the Dockerfile
> Let’s add a new line to the Dockerfile we’ve been using so far to create a copy of sum.py

However, up to this point the only docker image we've created is in the `basic` directory, so the initial modification steps needed to `Dockerfile` haven't been made. I just copied the Dockerfile from `basic` and added the `COPY` command and it seems to run ok.

**Comment by sstevens2** [comment]
Thanks @gcapes I noticed this too when I taught it a couple weeks ago.  I did the same where I copied the basic Dockerfile over.  Would you like to make a PR to add this change to the lesson?  If not, let me know and I'll add your suggested change.

**Comment by sstevens2** [comment]
Or alternatively, I'll update the `sum/Dockerfile` to have the basic as a starting point.

**Comment by gcapes** [comment]
Given the time that has passed since creating this issue, I cant really remember the details so I'm happy for you to make the changes :)
