### ISSUE TITLE
Adding Image of Cookie Cutter Analogy

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#192]
The below feedback includes an image I think would be good to include in the lesson. @mkuzak did you make this image?  Would you like to contribute it to the lesson?

> Name: Mateusz Kuzak
> Institution: The Netherlands eScience Center
> Date Taught: 2021-03-23
> https://esciencecenter-digital-skills.github.io/2021-03-23-containers/
> Was this taught as a stand alone workshop or as part of another workshop / conference? stand alone
>What feedback do you have on the lesson? 
>Most of the things we shared elsewhere. One thing that was not captured anywhere is the analogy we used was that Dockerfies are like a design for the 3D printed cookie cutter, the 3D printed cookie cutter is the image and the cookie is the running container. Djura Smits made a graphic for it.
>![docker-cookie-cutter](https://user-images.githubusercontent.com/208443/128470197-db279b7b-5130-4cdd-a7bb-d17929cec605.png)

_Originally posted by @mkuzak in https://github.com/carpentries-incubator/docker-introduction/issues/23#issuecomment-894050604_

**Comment by mkuzak** [comment]
I think this was @dsmits, Djura can you confirm?

**Comment by jcohen02** [comment]
It would be great if we could include this graphic in the lesson material. @dsmits, if you're happy for us to include this, can you let us know if there are any attributions that we need to include for any of the images used in the graphic, or are they all under a CC0 or public domain-style licence? (and we'll of course give you attribution as the author of the complete graphic). Thanks.

**Comment by sstevens2** [comment]
@dsmits replied in issue #23 

https://github.com/carpentries-incubator/docker-introduction/issues/23#issuecomment-1337562806

**Comment by aturner-epcc** [comment]
Relates to this comment from [peer review](https://github.com/carpentries-lab/reviews/issues/15)

> Introducing containers - Is it possible to show a graphical representation of how containers are created from Dockerfile?
