### ISSUE TITLE
Working interactively with Docker

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#2]
Hi @dme26!

I added a section to the lessons where I showed them how to interactively work in a docker container.  While it int as reproducible of a way to build images, it is often still useful.  I often work interactively with a container while I'm writing my dockerfile to check that the commands will work as expected.  Someone in the workshop suggested maybe adding a section that mimics that workflow.

It is at the bottom of this lesson, the section called "Creating an image interactively".  It might need to go elsewhere in the lessons.  I also think it might need to be a better example. https://uw-madison-datascience.github.io/docker-introduction/05-creating-container-images/index.html

Let me know what you think.

**Comment by ChristinaLK** [comment]
Running interactively has been added to the third episode, but could be moved later or into its own section.

**Comment by sstevens2** [comment]
Thanks Christina! I'll close this issue.
