### ISSUE TITLE
docker image vs container check

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/docker-introduction#20]
I (Christina) am guilty of using image vs container interchangeably. Should check the whole lesson for correctness. :P

**Comment by dme26** [comment]
How about we add a figure akin to Docker's https://docs.docker.com/storage/storagedriver/images/sharing-layers.jpg ? I think that discussing layers more explicitly might help learners differentiate between images and containers (also see #6 ). Docker's documentation at https://docs.docker.com/get-started/overview/ describes containers as "a runnable instance of an image".

**Comment by ChristinaLK** [comment]
I'll have to think about that. Would teaching about layers make it easier for learners to form a mental model around containers? If yes, I think it's worth adding that in, probably in the section where they build their own container from a Dockerfile. 

If we do add layers, I'm not a huge fan of that sharing-layers figure -- I think we could create our own that doesn't include as much implied technical detail.

**Comment by dme26** [comment]
Thinking about layers is highly useful for me, but I'm probably not a useful data point.

A different way to visualise layers might be building a picture up by superimposing layers of transparancy material? The (Docker) image you share is a stack of transparency sheets clipped together. Any container adds a transparency sheet on top of the image stack to scribble on. (This analogy becomes somewhat less effective when talking about multiple containers created from the same image though... It also doesn't explain how layers can (appear to) delete files otherwise seen in the layers below, but I think that's less of an issue.)

**Comment by ChristinaLK** [comment]
I like the transparency analogy. I think layers are useful for explaining images, but not explaining the differences between images + running containers.

**Comment by sstevens2** [comment]
Related to the use of container and image, I did a docker preview recently and the small group respond well to the following analogy for images and containers.  Images are the cookie cutter that specifies what the cookie will look like.  Container is the cookie that is actually created that you can use (eat).

**Comment by sstevens2** [comment]
Since this issue of using container/image has come up again in #40.  I'll try to get it in progress soon.

**Comment by gajowi** [comment]
I also like the transparency (stack) analogy. I do wonder if young people will get it :-P
You can extend an analogy too far but this one may usefully extend in a couple of ways.
Overriding files in an image by adding a new layer is a bit like putting 'whiteout' on the top slide, then adding new content on top. FWIW the old content is still underneath, but you can't see it unless you go digging. When you take an image and run in as a container, you get an extra run-time layer that holds any new files or changes to existing files. This is related to building images. Each addition is done by running the image as a container and running one or more operations that add files to the run-time layer, which is then saved along with the existing layers as a new image. The image is the stack of layers.

It would probably be too much to talk about whether you look through the slides from above or below... Its more like looking through to a blank sheet than shining light through the stack of slides... The docker run-time might need to look through many layers to decide where a file actually is - then to copy a file to the top/runtime layer (and mask a lower/old copy) to make alterations. It also need to check if any volume mappings are in scope. There are limitations that are not intuitive if, as most people, you are used to working with a regular filesystem and not with a stack of overlays (if you don't want to just consider the whole thing as a black-box).

FWIW I don't like the cookie cutter analogy - even if feedback was good. It makes one important distinction but goes no further. Even so, a better complementary analogy might be the recipe vs the dish. Each layer has a set of recipe instructions. The final layer is the container run-time where you get creative but normally throw away the resulting layer and keep the output you actually want. A lot of the value is in codifying recipe steps that you can and will reuse (as slides/layers) with appropriate granularity.
