### ISSUE TITLE
Explaining the term "dependencies"

### ISSUE THREAD

**Issue by jdamerow** [carpentries-incubator/docker-introduction#201]
I'm wondering if the term "dependencies" should be explained at the beginning of the lesson (https://carpentries-incubator.github.io/docker-introduction/introduction/index.html). It's used quite frequently throughout and issues with dependencies are a good reason to use containers, but someone who hasn't had too much experience with software development/programming might not really understand what the term refers to.

Maybe adding a note box that says something like "A dependency is a piece of software or programming module that another software depends on. For example, if you develop an application that uses a PostgreSQL database then PostgreSQL is a dependency of your application. You can't run your application if PostgreSQL does not run properly."

Maybe it's obvious but it seems like one of those terms that we think everybody understands because it has meaning, but that might not be obvious to people with less technical background. :)

**Comment by aturner-epcc** [comment]
I think this is a very good idea and ties into the review issue on adding a glossary. I think a callout box for this specific term (as it is used so much) and an entry in the glossary is the way to go.
