### ISSUE TITLE
Convert to Workbench format

### ISSUE THREAD

**Issue by joelnitta** [carpentries-incubator/docker-introduction#217]
There is a tool do this, but I haven't tried it myself: https://github.com/carpentries/lesson-transition#readme

**Comment by multimeric** [comment]
Has anyone made a start on porting this? If not, I might do it myself, since I also need the updated lesson.

**Comment by aturner-epcc** [comment]
I don't think anyone has started this yet. The new workbench format is so awful to both develop in and use for teaching compared to the old Jekyll format, there has been little appetite to convert it so far. However, I suspect we have no real choice here so if you want to go ahead, it would be much appreciated.
