### ISSUE TITLE
Autobuild of new carpentries workbench format fails because of confliciting branch names

### ISSUE THREAD

**Issue by aturner-epcc** [carpentries-incubator/docker-introduction#222]
@sstevens2 Do you have permission to rename the default branch from "gh-pages" to "main" so the automated build can run and output ot an orphaned gh-pages branch? I do not have permission on the repo to do this.

**Comment by sstevens2** [comment]
@aturner-epcc is this still an issue?  I thought @dme26 fixed this in #221

**Comment by aturner-epcc** [comment]
Yes, this is fixed. I'll close the issue now.
