### ISSUE TITLE
Improve alternative text for any images

### ISSUE THREAD

**Issue by aturner-epcc** [carpentries-incubator/docker-introduction#224]
Address reviewer comment from [peer reveiew](https://github.com/carpentries-lab/reviews/issues/15)

> The alternative text of all figures is accurate and sufficiently detailed.
> Large and/or complex figures may not be described completely in the alt text of the image and instead be described elsewhere in the main body of the episode.

**Comment by jcohen02** [comment]
Currently no images but there will be one added from issue #192.
