### ISSUE TITLE
Add section on target audience

### ISSUE THREAD

**Issue by aturner-epcc** [carpentries-incubator/docker-introduction#225]
Address comment from [peer review](https://github.com/carpentries-lab/reviews/issues/15)

> The target audience identified for the lesson is specific and realistic.
> I am not sure I saw a section highlighting the target audience, has this been mentioned?

**Comment by jcohen02** [comment]
_From offline discussion:_ A quick overview of the general target audience - people who are looking to develop their knowledge of container tooling to support the research work and enhacing reproducuiblity. Also note that this course is a beginner level course that is suitable for people who have no experience of containers.
Then provide more detail on specific roles that might benefit from this course - researchers, technical professionals - details of experience levels and areas of work.
Is there something in the new template for where this is supposed to fit?

**Comment by jcohen02** [comment]
Take a look at learner profiles in the new template. ( `profiles` directory with a `profiles.md` file in it).
