### ISSUE TITLE
Define "container"

### ISSUE THREAD

**Issue by multimeric** [carpentries-incubator/docker-introduction#250]
In the `introduction` episode, the content talks around the idea of a container, but never really defines it. I think it would be helpful to have a sentence with "a container is..."

**Comment by aturner-epcc** [comment]
@multimeric Thanks for the feedback. I had a look through and I agree that this would be a helpful addition to the material. While it does describe what a container is across the introduction and my experience is that leaners come away from this episode with a good concept of what a container is adding an explictit snetance would be useful.

The Docker description of a container seems to be a useful starting point:

> A container is a standard unit of software that packages up code and all its dependencies so the application runs reliably from one computing environment to another.

**Comment by multimeric** [comment]
Yeah, I like that definition. Though I wonder if such things are classed as their IP?

**Comment by aturner-epcc** [comment]
I cannot imagine it is a problem if we give credit and point to the source.
