### ISSUE TITLE
Adding maintainers

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#26]
@ErinBecker @fmichonneau What is the best way to add maintainers to this repo?  We would like to add @ChristinaLK and maybe others in the near future.

**Comment by fmichonneau** [comment]
I've made you an admin of the @carpentries-incubator/docker-introduction-maintainers team which should allow you to add people to it. They will have then "Maintain" access to the repo. Would that work for you?

**Comment by dme26** [comment]
Thanks François!

**Comment by sstevens2** [comment]
Thanks François!

**Comment by sstevens2** [comment]
Looks like only org owners can invite people to that group @fmichonneau.  I tried to add Christina and got the following.
<img width="618" alt="Screen Shot 2020-08-19 at 1 38 45 PM" src="https://user-images.githubusercontent.com/5558419/90676303-68e72b80-e221-11ea-819c-201391f1da1e.png">

I'm also looking to add @aturner-epcc and maybe @jcohen02 too.

**Comment by ErinBecker** [comment]
I'm on it!

**Comment by ErinBecker** [comment]
@sstevens2 - those three people should have just received invitations to the docker-introduction-maintainters team. Once they accept the invitation, they will have Maintainer level access to the repo. Please let me know if you need anything else!

**Comment by sstevens2** [comment]
Thanks @ErinBecker !

**Comment by jcohen02** [comment]
Invite received, many thanks @ErinBecker, @sstevens2.
