### ISSUE TITLE
Lesson title

### ISSUE THREAD

**Issue by jcohen02** [carpentries-incubator/docker-introduction#27]
The title of this lesson is fairly generic and it is, I think, equally applicable to the new [singularity-introduction](https://github.com/carpentries-incubator/singularity-introduction) lesson that has just been added to the carpentries-incubator.

Indeed, the material in the singularity-introduction lesson was originally developed and taught as an extension to this material in [this workshop](https://github.com/imperialcollegelondon/2020-07-13-Containers-Online).

While the Singularity lesson has been spun out into a separate set of material, to maintain a link with this material (and support the case where they may be taught together as part of a workshop) it has been given the title "_Reproducible computational environments using containers: Introduction to Singularity_".

Is it worth considering a renaming of this lesson to "_Reproducible computational environments using containers: Introduction to Docker_", or, to avoid confusion should the Singularity lesson be renamed to something different, such as "Introduction to Singularity"?

See [issue 3](https://github.com/carpentries-incubator/singularity-introduction/issues/3) in the singularity-introduction repo for further information/discussion.

**Comment by ChristinaLK** [comment]
@jcohen02 I agree that giving a matching title that includes the specific container technology is a good idea.

**Comment by ChristinaLK** [comment]
Closed by #29
