### ISSUE TITLE
new DockerHub limits

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/docker-introduction#28]
We should add something to the lesson about the new Docker Hub limits, especially if people are using Docker containers for reproducibility purposes.

**Comment by aturner-epcc** [comment]
@ChristinaLK Fancy seeing you here! Hope you are keeping well.

Can I check what limits you are referring to here? Is this the 100 pulls in 6 hours or the 6 month retention? The latter seems a bigger deal for reproducibility. If so, I agree that this needs to be made clear.

**Comment by ChristinaLK** [comment]
Yes, I was more concerned about the 6 month retention.

**Comment by ChristinaLK** [comment]
It looks like your PR adding the reproducibility section address this @aturner-epcc ! @sstevens2 can you confirm that the final episode has enough detail about how to archive a container image, and if so, close this issue?

**Comment by sstevens2** [comment]
I think maybe we should add a link in that episode to some documentation (preferably from dockerhub) of the new limits.  I'm struggling to find a good one.  I mostly found [this rate limit page](https://docs.docker.com/docker-hub/download-rate-limit/) but it isn't particularly easy to read and only addresses rate limits not the 6 mo retention issue.

**Comment by ChristinaLK** [comment]
I think this link is good but don't know how long it will be "live": https://www.docker.com/pricing/resource-consumption-updates

**Comment by jcohen02** [comment]
It looks like the changes to the image retention policy won't now be coming in for a little while (https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/) so there's still a little time to find a suitable set of information on this...

**Comment by ChristinaLK** [comment]
Do we want to use the link from @jcohen02 's comment for now? or close this issue?

**Comment by chendaniely** [comment]
for retention/reproducibility what if we promote using figshare/zenodo/github to host the dockerfile itself? so people are not relying on pull images and building the images locally?
