### ISSUE TITLE
Controlling the windows env more

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#3]
I had 3 extra laptops just in case there were errors I couldn't solve with docker on the fly.  It might be my lack of experience with windows but all 3 of them ended up going to people with windows and a majority of the errors were on windows machines.

I was thinking maybe we could try to have them to use the quick start terminal or a specific shell to try to standardize the approach so we can rule those out as possible reasons why some folks are getting errors?

**Comment by ChristinaLK** [comment]
Can this be closed, as we have other Windows issues open now?

**Comment by chendaniely** [comment]
probably, the WSL2 stuff may have fixed this problem https://github.com/carpentries-incubator/docker-introduction/issues/98
