### ISSUE TITLE
Survey for Learners and Instructors

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#33]
@tobyhodges we talked a bit about this when we met last week but it came up again in my meeting today with @aturner-epcc and @jcohen02.  We thought would be nice to have a survey for learners and maybe one for instructors to get feedback from the individuals using the lesson.

@tobyhodges Were you thinking something that could be use for any incubator lesson?  If so, anything we can do help construct that survey?

**Comment by sstevens2** [comment]
@tobyhodges  I think you created a survey we can reuse for learners pilot workshops but I don't quite remember where to find it.  Could you point me in the right direction?

**Comment by tobyhodges** [comment]
[The post-pilot workshop survey template](https://docs.google.com/forms/d/1OGCQBotD2nOJkc7KpFZLhFfb3EBcxEDwHz_3p48qz3U/template/preview).

**Comment by sstevens2** [comment]
Created copy of the survey @tobyhodges linked above and gave access to the maintainers.  @aturner-epcc and @dme26 Let me know if I added the wrong email to access it.

The fillable form can be found here - <https://forms.gle/jnxRPdMJeBj8eFZX8>.  I will add this to the pinned issue about feedback from pilots.
