### ISSUE TITLE
Issue installing python on alpine

### ISSUE THREAD

**Issue by MCMaurer** [carpentries-incubator/docker-introduction#36]
Hi there,

I was just working through the "Creating your own container images" episode, but I ran into an issue with the following command: `/# apk add --update python py-pip python-dev`.

I got the following error message:

```
ERROR: unsatisfiable constraints:
  python (missing):
    required by: world[python]
  python-dev (missing):
    required by: world[python-dev]
```

Everything else with the `alpine` image has worked so far! Additionally, the next exercise, installing R, worked just fine.

**Comment by sstevens2** [comment]
Thanks for reporting this issue @MCMaurer!  I'll schedule some time to look at this in the next couple days.

**Comment by sstevens2** [comment]
Thanks again for reporting this @MCMaurer !  It looks like the package manager `apk` doesn't have a general `python` package anymore and requires that you specify if you want python2 or python3.  I've put in pull request #39 to try to fix this issue in the lesson.  If you'd like to give the changes proposed a try and give us feedback, we would really appreciate it!

**Comment by MCMaurer** [comment]
Hi @sstevens2, looks like that did the trick! I ran `apk add --update python3 py3-pip python3-dev` and that worked perfectly. I was also able to add the changes to the Dockerfile and successfully build the new image. Thanks!!

**Comment by sstevens2** [comment]
Wonderful. Thanks @MCMaurer !

**Comment by MCMaurer** [comment]
Sure thing, and thanks for the wonderful lesson, I've found it super helpful so far!
