### ISSUE TITLE
image vs container

### ISSUE THREAD

**Issue by gajowi** [carpentries-incubator/docker-introduction#40]
I've just read through the training (nice!) and have some comments and could potentially contribute. I'll start with a general description of a specific issue.

The use of the terms image and container could be more precise and consistent. I think the accepted/defined usage is that the image is the static artefact and the container is a running instance (which started as/from a particular image). This may link with [Section on Layers](https://github.com/carpentries-incubator/docker-introduction/issues/6) 

Also, the description of 'prune' and images left behind by exited containers is relevant. The container has an additional runtime layer for any filesystem changes made on-the-fly.

**Comment by aturner-epcc** [comment]
Thanks for taking the time to look through and make comments @gajowi . I agree that we certainly want to be consistent with the terms and if you have contributions that could improve this, they would be most welcome. Alternatively, if you have spotted things that can be fixed and do not have the time to issue your own PR, then please feel free to point out anything in particular you spotted and we can get the improvements in.

There is definitely scope for improvement and more precision in the descriptions of particular operations (such as `prune`) and the descriptions of layers (see also #6) and I think some diagrams could also go a long way to helping introduce concepts around layers.

**Comment by sstevens2** [comment]
Glad to hear you are interested in the lesson.  If you have time for PRs or individual issues on things you note that need to be fixed that would be great!  Contributions welcome!  

This issue seems to be the same as #20 and #6 so I'm going to close it but please feel free to add additional comments in those issues.
