### ISSUE TITLE
"tag" is confusing

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/docker-introduction#43]
The lesson talks about tags in the image names `OWNER/REPO:TAG` but the `docker tag` syntax has an entirely different meaning -- it's like the whole label or name for the container, not just the version tag. We should probably rename the `:TAG` to something else to keep those from being confused. :(

**Comment by ChristinaLK** [comment]
Or just don't talk about `docker tag`. ;)

**Comment by jsgro** [comment]
I think that it important to talk about "tag" because if the downloaded image does not harbor the ":latest" default but has a tag associated with it it is mandatory to use the tag otherwise docker run will say the image does not exist. For example I have ubuntu:latest as well as ubuntu:16.04 in my lists of images. I would have to specify :16.04 if I want that version. And if I had no :latest version a command like "docker run --rm -it ubuntu" would fail.

**Comment by ChristinaLK** [comment]
@jsgro I do want to talk about tags, I just don't want to have people confused between the `docker tag` command and the **version** tag for an image, which are slightly different things. Do you think it would make more sense to just omit talking about `docker tag` or when talking about version tags, to call them "version tag" specifically (instead of just "tag")?

**Comment by jsgro** [comment]
I think that it would be best to talk about both... first because it is useful and also to point out what you said: not to confuse them. 
ALso, they are related as one can add a `:tag` to an image with the `docker tag` command

**Comment by jcohen02** [comment]
@ChristinaLK @jsgro I'm inclined to agree that it would be good to talk both about tags and the `docker tag` command. I've never really thought about this before but I suppose the `docker tag` command could be considered to be slightly misleadingly named in the sense that, if I understand things correctly, it's more like an _alias_ command?

Nonetheless, the help for the `docker tag` command does highlight tags in the same way as covered in the lesson, it shows that the command is taking `SOURCE_IMAGE[:TAG]` and creating `TARGET_IMAGE[:TAG]` where I'm assuming that `SOURCE_IMAGE` and `TARGET_IMAGE` are equivalent to the `OWNER/REPO` part of an image name as explained in the lesson. It's just that despite being called `tag` the command doesn't actually require you to add a tag to the resulting image name? Hope this makes sense and I'm not confusing the discussion!

**Comment by jsgro** [comment]
The main point for me is: if you download an image from the hub that does not have a `:latest` tag, then in your listing of image `docker images` it will only appear with that tag. Then, when calling that image to work in `docker run` if you don't specify the `:tag` then it will say that the image does not exist. Here is an example of such an image that I get from my list with `docker images`:

`biocontainers/emboss                 v6.6.0dfsg-7b1-deb_cv1   bc147a9dd825   15 months ago   638MB`

There is no *alias* of this one with `:latest` in my list as this is how it was downloaded. Therefore to use it it is necessary to have that long, ugly `:tag` on the command line when starting with `docker run`.

For a casual user like me this is the most critical part to understand.

**Comment by ChristinaLK** [comment]
I guess I want to avoid something thinking that `docker tag` *only* refers to the final part of a fully qualified image name (`OWNER/REPO:TAG`) when in reality it refers to the whole thing. 

All that to say, I think the lesson is probably okay as is, but I could easily see people having questions about this.

**Comment by ChristinaLK** [comment]
Given that other people don't seem too concerned about this, I think we can leave as is for now.
