### ISSUE TITLE
Update Windows Install directions for Docker Desktop?

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#47]
I've not used docker desktop for windows and haven't tried it for the whole workshop yet.  Think we should try it out and then update the install directions.

**Comment by jcohen02** [comment]
I've actually just updated these instructions in the last few days (although I have to say that I think they probably need testing) for the [course run today/yesterday](https://epcced.github.io/2020-12-08-Containers-Online) covering docker and singularity. I was intending to feed these updates back into this repo so I'll open a PR with these updates in the next day or so.

**Comment by sstevens2** [comment]
Funny we are running this today too!  So expect more issues and PRs.

**Comment by jcohen02** [comment]
Great 🙂 (sorry that I didn't contribute my changes back a bit earlier, updates were a little last minute...)

**Comment by sstevens2** [comment]
@jcohen02 Can you confirm this is resolved? or not?

**Comment by jcohen02** [comment]
Apologies for not linking to this from the PR, these updates were actually merged in PR #51 so I'm going to close this issue now.
