### ISSUE TITLE
Replace dme26 with something appropriate

### ISSUE THREAD

**Issue by dme26** [carpentries-incubator/docker-introduction#5]
My identifier dme26 should probably be removed from code listings. I don't actually mind if it stays there, but the "replace with your ID" pattern must be common across, e.g., Carpentry lessons, and this lesson should ideally adopt good/better/best practice in this regard.

**Comment by sstevens2** [comment]
In my fix I replaced docker hub IDs with alice to match the current version in the other lessons and then later lessons to the incubator id.

**Comment by dme26** [comment]
Perfect, thanks for this—I'll look for the Alice, etc., sequence elsewhere in the Carpentries lessons if I need more than an Alice if I'm adding / tweaking content in other parts of the lesson.

**Comment by sstevens2** [comment]
I'm thinking Alice probably came from this - https://en.wikipedia.org/wiki/Alice_and_Bob
