### ISSUE TITLE
Shell access to an already running container - Container name

### ISSUE THREAD

**Issue by jsgro** [carpentries-incubator/docker-introduction#57]
There might be a situation where a container is already running, but we cannot turn it off at the moment for various reasons. (For me it was because I had tested/added lengthy modifications but I had --rm in the original command so exiting would have destroyed my changes.) 
I also wrote a blog on this: https://bcrf.biochem.wisc.edu/2019/11/01/docker-notes-shell-access-to-running-container/

There are 2 concepts to think about:

1. entering a container that is already running
2. the container name

The container name is randomly given (and can be seen with "docker ps") but can also be specified by the user using the "`--name`  _`myname`_" method so that the name is always the same.

The name can then be more easily used to run a command from a separate terminal to enter a shell of that container which here could be: `docker exec -it` _`myname`_   `/bin/bash`

I suppose that this would be useful information.

**Comment by ChristinaLK** [comment]
@jsgro can you say more about the type of container development workflow or use case that would require connecting to an already running container?

**Comment by jsgro** [comment]
I don't have a standard workflow example. For me it was when I was trying to make some image/container work, perhaps with Web... I had to install lots and lots of `libraries` and then many dependencies...etc. I needed to see some setting within but could not because a process was running. I think it might have been the case where I had started the container with `--rm` so stopping it would remove all the changes. Also the container had been started with `-d` as a "detached (hence no more Terminal access) - 
I don't think that this is critical for most users, but it is certainly a nice "trick" to know about if you cannot stop the container, it is detached etc.

**Comment by dme26** [comment]
In a co-working sprint we agreed that our focus for now for the core material is on containers that aren't persistent (i.e., they start up, do something, then shut down). Nonetheless, the extra material certainly uses persistent containers in the context of Jekyll website generation, for example. Some planned learner pathways may provide good opportunities to explore persistent containers in more detail, including running shells within them.
