### ISSUE TITLE
How to override ENTRYPOINT using docker run

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/docker-introduction#58]
Entrypoint is a great feature... However, for the untrained docker user (like me) it can be extremely frustrating to not know how to "get into" the container and check things out, for example because the entrypoint command fails and then the container stops and we don't know why. 
Because of that I wrote a blog about this and how to by-pass the entrypoint: https://bcrf.biochem.wisc.edu/2019/10/31/docker-notes-bypass-entrypoint/

which contains 2 references to other blogs:

- How to properly override the ENTRYPOINT using docker run: 
https://oprea.rocks/blog/how-to-properly-override-the-entrypoint-using-docker-run/
(archived 11NOV 2019: bit.ly/2QFlGne)

- Docker RUN vs CMD vs ENTRYPOINT:
https://goinbigdata.com/docker-run-vs-cmd-vs-entrypoint/
(archived 25MAR 2019: bit.ly/35pg8Bj )

This may be the only way to get into a container and use a program even if the entrypoint command fails.

_Originally posted by @jsgro in https://github.com/carpentries-incubator/docker-introduction/issues/41#issuecomment-742835999_

**Comment by ChristinaLK** [comment]
This could be a callout or note in the lesson episode on using `docker run`.

**Comment by sstevens2** [comment]
I agree this would probably be best in a callout in the section using `docker run`.

**Comment by hvwaldow** [comment]
That is covered in #63 ([commit](https://github.com/carpentries-incubator/docker-introduction/pull/63/commits/89a6a71693eaeeee39224510bfcfff4ab0b965d8#diff-d0cf2de18019fb7b377df785ccd66828f5afcba77a029c36aa442c54324f0a3d))

**Comment by ChristinaLK** [comment]
closed by #63
