### ISSUE TITLE
Jekyll command error in Lesson 9

### ISSUE THREAD

**Issue by jsgro** [carpentries-incubator/docker-introduction#62]
In Lesson 9 -
https://carpentries-incubator.github.io/docker-introduction/07-containers-for-continuous-integration/index.html

I tested the command below in both macOS and Windows10:
`docker run --rm -it -v ${PWD}:/srv/jekyll -p 127.0.0.1:4000:4000 jekyll/jekyll:3.7.3 make serve`

In both cases there is a series of errors.
IN THE END the correct way to do this is changing the 2 things: the `-p` option and the requested command. The following should work for all:

```
docker run --rm -it \
  --volume="$PWD:/srv/jekyll" \
  -p 4000:4000 jekyll/jekyll:3.8.5 \
  jekyll serve
```
Inspired by https://martinpeck.com/jekyll/blog/containers/2019/02/02/build-and-deploy-jekyll-with-docker-part1/

The tricky part is that the directory contains a `Makefile` that we'll run within the container... but itself will make a container, hence the HTTP never gets to the Mac or Windows PC... (as far as I understand)

Changing `make serve` to `jekyll serve` makes the difference: now the HTTP server will be made within the docker container just started.

NOTE: there was another line `--volume="$PWD/vendor/bundle:/usr/local/bundle" \` which I removed as I was getting time-stamp error (a `Gemfile.lock` was created as well as a `vendor` directory that made it difficult for me to test various commands...)

**Comment by aturner-epcc** [comment]
Yes, I spotted this issue when preparing for the workshop this week and updated in our local version. I will raise a PR to get the correct command in here.

I did not need to change the port option though - just `make serve` to `jekyll serve` and I went for `jekyll latest` and it worked fine for me.

**Comment by sstevens2** [comment]
@aturner-epcc Checking on this, are you working on the PR or is it already merged?

**Comment by jcohen02** [comment]
This is, in part, linked to the discussion in #74. It would be good if we can update this to something that works on MacOS, Windows and Linux but I'm still not sure what the best fix for #74 is, so maybe it's better to fix this first and then make a further update to address Linux later.

**Comment by ChristinaLK** [comment]
Was this fixed in the sprint?

**Comment by sstevens2** [comment]
Think it can be close with #74 as #99 seemed to solve the issues with jekyll.
