### ISSUE TITLE
Shared Folder and $PWD nomenclature

### ISSUE THREAD

**Issue by jsgro** [carpentries-incubator/docker-introduction#64]
Sorry to bother you with what might feel a trivial thing... but it could be frustrating in some cases.

On the lesson pages there are currently 2 (two) ways that the "*current directory*" is referenced: **`$PWD`** and also **`${PWD}`**. They both work on macOS, but **`$PWD`** will Fail on Windows PowerShell (I just tried again.) 

In fact when I learned about this I learned it with parenthesis as **`$(pwd)`** which works on macOS and Linux but not on Windows. (I just verified on Windows.)

Also, even though I am not able to test this, I would think that UPPercase formats would fail in Linux because of case-sensitive shell, while the Mac is (usually set to be) case insensitive.

Therefore the most common format that should work on macOS, Linux and Windows PowerShell is likely to be: **${pwd}`** with curly brackets *and* lower case.

I did note the `cmd.exe` format `"%CD%"` which completely different but is a useful addition for a few people.

**Comment by jsgro** [comment]
CORRECTION:

I just spent 5 min on macOS with **`${pwd}`** and it does not do the job! so UPPERCASE is necessary in curly brackets **`${PWD}`** but for parenthesis on macOS it could be either upper or lower case as `$(pwd)` or `$(PWD)`.

**Comment by jsgro** [comment]
Specifying a working directory with -`w`

On page "[Creating More Complex Container Images](https://carpentries-incubator.github.io/docker-introduction/05b-advanced-containers/index.html)" it is explained to specify `/temp/sum.py` for the command to work. This works OK as it is a one-time command that is non-interactive.

But on occasion I have found it much more useful to specify the working directory immediately on the command line with `-w` so in this case the command would be (change to `python3` to avoid error and added `--rm` to avoid accumulation of many stopped containers) :

`docker run --rm -v ${PWD}:/temp -w /temp  alice/alpine-sum python3 sum.py`

*Note*: `sum.py` could also be written as `./sum.py`

Defining working directory this way with `-w` is also useful for interactive session.

**Comment by aturner-epcc** [comment]
> CORRECTION:
> 
> I just spent 5 min on macOS with **`${pwd}`** and it does not do the job! so UPPERCASE is necessary in curly brackets **`${PWD}`** but for parenthesis on macOS it could be either upper or lower case as `$(pwd)` or `$(PWD)`.

Braces with uppercase ${PWD} are the way to go as these reference the PWD environment variable correctly on Linux, macOS and Windows Powershell.

@jsgro The reason that parentheses $(pwd) works in lowercase on macOS and Linux is that this is running the `pwd` command rather than referencing the env variable. Dollar with parentheses is the way you run a command in bash/zsh and return the result of the command. As Powershell is not bash/zsh, this does not work here.

**Comment by aturner-epcc** [comment]
> Specifying a working directory with -`w`
> 
> On page "[Creating More Complex Container Images](https://carpentries-incubator.github.io/docker-introduction/05b-advanced-containers/index.html)" it is explained to specify `/temp/sum.py` for the command to work. This works OK as it is a one-time command that is non-interactive.
> 
> But on occasion I have found it much more useful to specify the working directory immediately on the command line with `-w` so in this case the command would be (change to `python3` to avoid error and added `--rm` to avoid accumulation of many stopped containers) :
> 
> `docker run --rm -v ${PWD}:/temp -w /temp  alice/alpine-sum python3 sum.py`
> 
> *Note*: `sum.py` could also be written as `./sum.py`
> 
> Defining working directory this way with `-w` is also useful for interactive session. 

I think this option would be a useful addition to the material but I also think there is value in keeping the explicit path for the first time this command is run to prompt the discussion about differing paths on the host and in the container. Maybe add a callout demonstrating the `-w` option?

**Comment by ChristinaLK** [comment]
It sounds like @jsgro has introduced two issues here -- inconsistency in `$PWD` and adding `-w`. I actually did use `-w` as an example the last time I taught this, so I think it could be added in the text or a callout pretty naturally. I did that *after* going through `-v` a few times.

**Comment by sstevens2** [comment]
I like the idea of adding `-w` as a callout in the lesson.

Sounds like we should also update the lesson to include `${PWD}` for the volume mount so this will work across mac/linux/windows.

**Comment by jsgro** [comment]
> > CORRECTION:
> > I just spent 5 min on macOS with **`${pwd}`** and it does not do the job! so UPPERCASE is necessary in curly brackets **`${PWD}`** but for parenthesis on macOS it could be either upper or lower case as `$(pwd)` or `$(PWD)`.
> 
> Braces with uppercase ${PWD} are the way to go as these reference the PWD environment variable correctly on Linux, macOS and Windows Powershell.
> 
> @jsgro The reason that parentheses $(pwd) works in lowercase on macOS and Linux is that this is running the `pwd` command rather than referencing the env variable. Dollar with parentheses is the way you run a command in bash/zsh and return the result of the command. As Powershell is not bash/zsh, this does not work here.

@aturner-epcc - Thank you very much for this clarification! These various nomenclatures were confusing me. Now it makes much more sense. I'll adopt this `${PWD}` as the "standard" now that I understand the underlying meanings. Much appreciated. JYS

**Comment by abotzki** [comment]
> Defining working directory this way with `-w` is also useful for interactive session.

Related to the discussion about the `-w` flag. From attending two Docker courses and teaching one recently, I would really recommend to add the `-w` flag in the lesson. Once you understand the inside-outside thing with the container, it is so much more convenient to use the `-w` when running e.g. bioinformatics tools with docker containers.
BTW nextflow is using this flag when running workflows with the `-with-docker` flag.

**Comment by sstevens2** [comment]
I created a new PR with the `${PWD}` variable change. Should address the bug part of this issue. 

@jsgro,  @ChristinaLK, or @abotzki  would you want to make a PR adding a callout with the `-w` flag?

**Comment by abotzki** [comment]
@sstevens2 Yes, sounds fine with me. I am just wondering whether it fits seamlessly to the current content of the episode [Creating More Complex Container Images](https://carpentries-incubator.github.io/docker-introduction/05b-advanced-containers/index.html)  As far as I see the Python script sum.py does not create any file written to disk when running.
So, I would add a somewhat more complex example where e.g. a tool (still to check what tools is most easy to use) would create some output files.
Does this make sense to you? Thanks.

**Comment by sstevens2** [comment]
Think so @abotzki.  Sounds like we might need to add another script to add this enhancement with the `-w` flag.

**Comment by abotzki** [comment]
hi @sstevens2 recently, in the framework of a hackathon to create reusable exercises, we have made an example which could be useful in this use case: https://containers-workflows.readthedocs.io/en/latest/containers/exercises.html - what do you think?

**Comment by jsgro** [comment]
Greetings @abotzki  - I just went through your exercise page and here are a few constructive comments and errors found, knowing that this is not a final version:

* Top: " on a fastq-file " should probably not be hyphenated
* Learning outcome: "Set the default user and group with the `-u` option" should probably be "with the `-u` and `-g` options" as this is what is learned.
* "Use the option `--mount` to bind mount a host directory to a container" -->> `--mount` is used...but now I see it in the Solutions page.
* unfinished phrase: "Try to answer the following questions and think about how the"
* Section 3: `$(pwd)` (See our previous discussion that the "universal" format is `${PWD}` so that it works on all platforms
* End of Section 3: `--user $(id -u):(id -g)` - Missing `$`, correct works with `--user $(id -u):$(id -g)` (I now see it correctly in the Solutions page) - Question: would this notation work on Windows? I tried replacing with `{}` on my Mac and it does not work that way.
* Section 4 exercise calls for files `WTXXX.fq.gz` but the files downloaded earlier allegedly for this exercise are  `ecoli_reads.tar.gz`

I did not do the `trimmomatic` exercise.

About downloading the container: I had to first log-in with `docker login quay.io` but perhaps this is said earlier in the course. 

I did learn about `-u` and `-g` as well as the global version `--user $(id -u):$(id -g)`

I have found it easier to have 2 terminals open so that I could check on permissions more easily from the 2nd Mac Terminal.

FYI I have written a Docker tutorial that may be useful, the part using FASTQC is on this link:
https://static-bcrf.biochem.wisc.edu/tutorials/docker/Docker_03.html
The general tutorial materials is on this link: 
https://bcrf.biochem.wisc.edu/docker-beginner-for-biologists/

Best wishes for your course.
Jean-Yves

**Comment by abotzki** [comment]
hi @jsgro Jean-Yves, thanks a lot for the thourough review. I'll add the changes to the exercise.
@sstevens2 how would you see such an exercise fit the whole curriculum? Thanks.

**Comment by jsgro** [comment]
@abotzki You're welcome. Here is another "odd" thing that I may be (or not) a mistake "somewhere." It is about exercise 4.2. "... extract the working directory (WorkingDir) using `grep`."
From the link earlier in the text (which by the way is called "here" but should be rephrased to be more specific for "accessibility" reasons) the working directory defined within the Dockerfile is stated as:

`WORKDIR /data/ `

But that is not the result I get, even testing for upper/lower case:

```
$  docker inspect quay.io/biocontainers/fastqc:0.11.9--0 | fgrep -i  WorkingDir
            "WorkingDir": "",
            "WorkingDir": "",
```

Perhaps there is something that I don't understand, but it seems to me that there is something off here.
