### ISSUE TITLE
Hint for /proc/version in Practice maker perfect challenge

### ISSUE THREAD

**Issue by markgdawson** [carpentries-incubator/docker-introduction#66]
In `Exploring and Running Containers` in the challenge `Practice Makes Perfect`, it wasn't obvious to me that `/proc/version` was the file to look at.

For someone new to linux, they might immediately start looking for the `/etc/os-release` file. In my case, I just gave up and looked at the answer, which arguably made it less useful for me than if there had been a hint about the file name.

**Comment by ChristinaLK** [comment]
I think it's a good idea to add a hint.

**Comment by sstevens2** [comment]
@markgdawson or @ChristinaLK Would you like to make a pull request with this change?

**Comment by markgdawson** [comment]
Hi @sstevens2, I no longer work in an area which provides any training. It might make sense for someone who delivers or works with the material to make the PRs.
