### ISSUE TITLE
Take a look at the Dockerfile. It looks similar to the one we used before, but it has an additional line with the COPY keyword.

### ISSUE THREAD

**Issue by markgdawson** [carpentries-incubator/docker-introduction#67]
In  episode "Creating More Complex Container Images", there is this line:

`Take a look at the Dockerfile. It looks similar to the one we used before, but it has an additional line with the COPY keyword.`

This implies I should see similar content in the Dockerfile to the file created in the previous exercise. But I see:

```
FROM <EXISTING IMAGE>
RUN <INSTALL CMDS FROM SHELL>
RUN <INSTALL CMDS FROM SHELL>
CMD <CMD TO RUN BY DEFUALT>
```

**Comment by ChristinaLK** [comment]
We should also check if the sample Dockerfiles have the right commands.

**Comment by sstevens2** [comment]
Think the dockerfile might be okay, just the language assumed you had another copy of it with the `COPY` line in it.  Created a PR changing this to ask the learner/instructor to add a `COPY` line. See #81 and let me know if that seems to solve the issue.
