### ISSUE TITLE
`jekyll serve` command rather than the `make serve` command.

### ISSUE THREAD

**Issue by markgdawson** [carpentries-incubator/docker-introduction#69]
In episode 
Containers used in generating this lesson
this sentence appears.

`In the preceding output, you see Docker downloading the image for Jekyll, which is a tool for building websites from specification files such as those used for this lesson. The line jekyll serve indicates a command that runs within the Docker container instance. The output below that is from the Jekyll tool itself, highlighting that the website has been built, and indicating that there is a server running.`

This seems to refer to the `jekyll serve` command rather than the `make serve` command.

**Comment by markgdawson** [comment]
After testing, it seems that (on my machine) the command is incorrect rather than the text:

`docker run --rm -it -v ${PWD}:/srv/jekyll -p 127.0.0.1:4000:4000 jekyll/jekyll:3.7.3 make serve`

**Comment by jcohen02** [comment]
I was just investigating this and it looks like there's another issue with running the example at the moment (see issue #74) - the issue highlighted here should be fixed anyway and I think there's possibly some slight rewording that can also be done to this section to clarify things further.

**Comment by sstevens2** [comment]
@jcohen02 If I'm understanding, we might want to wait to fix this one and update the language until #74 is fixed?
