### ISSUE TITLE
Add some use cases

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/docker-introduction#71]
The first episode talks about some of the rationale for using containers - would it be helpful to introduce specific use cases? Like: 
- run an existing container on your computer, to either use the tool inside or to test it out
- build your own container to share with your group or run on a shared system

This is *kind* of touched on when we talk about reproducibility and portability, but we never connect the lesson material with these kinds of specific examples.

**Comment by ChristinaLK** [comment]
I think this also might be helpful in determining scope of this lesson - we are *not* talking about best practices for building a production ready container for deployment on kubernetes, for example...

**Comment by ChristinaLK** [comment]
and this may all be in the lesson and I didn't read carefully, in which case, please close this issue. :joy:

**Comment by aturner-epcc** [comment]
I think this is a good idea and will het set scope/expectations. @ChristinaLK Do you want me to have a go at this or do you want to have a go first?

**Comment by ChristinaLK** [comment]
@aturner-epcc if you'd like to give it a shot, please do! my time is a bit extra scrunched these days.

**Comment by sstevens2** [comment]
Think this one might be closed? @ChristinaLK  @aturner-epcc I think this was related to a PR we merged already?

**Comment by aturner-epcc** [comment]
Yes, this was done in #72 so I will close this issue
