### ISSUE TITLE
Jekyll example used in "Containers used in generating this lesson" currently not working

### ISSUE THREAD

**Issue by jcohen02** [carpentries-incubator/docker-introduction#74]
The example used in the "_Containers used in generating this lesson_" episode (`_episodes/07-containers-for-continuous-integration.md`) currently seems to be broken.

When you try to run the example using the command provided:

```
docker run --rm -it -v ${PWD}:/srv/jekyll -p 127.0.0.1:4000:4000 jekyll/jekyll:3.7.3 make serve
```

You get an error:

```
Could not locate Gemfile or .bundle/ directory
make: *** [Makefile:26: serve] Error 10
```

It seems that the `Makefile` is trying to run `bundle exec jekyll serve` which relies on the various gem dependencies being installed by [_bundler_ ](https://bundler.io/) either in a global or local environment. For example, by convention, these dependencies would often be installed in the `vendor/bundle` subdirectory under the project.

Since we're using the jekyll docker container, we should have all the required dependencies installed globally and bundler shouldn't be required.

I was sure this was working originally and it looks like the `jekyll` command in the `Makefile` was changed in commit 4e1e6b02 from `jekyll` to `bundle exec jekyll`.

The options here are:
 - Add an instruction to the lesson requiring the installation of the dependencies before running the `docker` command (e.g. run `bundle install --path vendor/bundle`)
  OR
 - Change the command in the `Makefile` back to `jekyll`, although I'm not sure what unintended consequences this may have

At the same time, I'd recommend increasing the jekyll version to something more recent. For example, we could use 3.9.0 as listed in the [GitHub Pages dependency versions](https://pages.github.com/versions/) as the version currently used.

**Comment by fmichonneau** [comment]
I don't know if it's helpful to you here but here is the command that is used with the template to run it with Docker: https://github.com/carpentries/styles/blob/gh-pages/Makefile#L52-L60

**Comment by jcohen02** [comment]
Many thanks for the pointer @fmichonneau. Actually, I see that in that latest version of the `Makefile`, the `JEKYLL` variable is set to

```
bundle config --local set path .vendor/bundle && bundle install && bundle update && bundle exec jekyll
```

rather than `bundle exec jekyll` as we currently have in our `Makefile`. That will solve the problem by installing the dependencies.

**Comment by dme26** [comment]
I've copied across the invocation I used in a recent workshop. Apologies for the delay!

**Comment by dme26** [comment]
Do you mind @jcohen02 checking if this now works for you?

**Comment by jcohen02** [comment]
Thanks @dme26, do you happen to know if the jekyll docker image that you're now using with the `pages` tag tracks the recommended jekyll version for GitHub pages (i.e. as listed on the "[Dependency versions](https://pages.github.com/versions/)" page? I'm guessing it probably does.

No problem, I'll check now...

**Comment by dme26** [comment]
I've not checked that it's tracking the GitHub Pages version, but that would be good to do, so let's leave this ticket open for that... but also here's hoping that copying over what worked for me previously has fixed the more immediate breakage, meanwhile.

**Comment by jcohen02** [comment]
@dme26 your fix seems to work fine running on my local MacOS system (via docker). However, running on a remote Linux system, I'm getting errors. The jekyll image is downloaded, I then see:

```
Digest: sha256:a80baa7fc7837a8d7a912c71ba583156a3f97683b1d48bac39e32d2c8c2c974f
Status: Downloaded newer image for jekyll/jekyll:pages
```

...followed by a long pause (a few minutes)...followed by...

```
Could not locate Gemfile
```

I'm running the exact command shown in the lesson material on both systems:

```
docker run --rm -it -v ${PWD}:/srv/jekyll -p 127.0.0.1:4000:4000 jekyll/jekyll:pages jekyll serve
```

Given that this is running in the same docker container on both systems, I could only see that this could be the result of something different in the directory being mounted into the container (i.e. the `docker-introduction-gh-pages` directory being mounted at /srv/jekyll). I thought maybe during the long pause its installing some dependencies. Looking in the docker container while it was hanging seemed to show it's running `/bin/bash /usr/jekyll/bin/bundle install` in addition to a few other things.

I thought perhaps the different behaviour could be the result of previously having installed the ruby dependencies by running bundle install --path vendor/bundle in the directory prior to running the docker command, but this isn't the case in my tests, I've downloaded and unzipped the contents of the gh-pages branch from GitHub as described in the lesson material. I'm investigating further.

**Comment by jcohen02** [comment]
The issue described above (getting `Could not locate Gemfile` when running the jekyll example on Linux) is a permissions issue. Not sure if something has changed or whether I'm missing something here but when running on MacOS, docker maps the current user on the host system to `root` inside the container.

This means that if I unzip the `gh-pages.zip` file downloaded from GitHub on my host system, the files are owned by the current user (i.e. my user). When I then run the container and bind the current directory into that container, I am `root` within the container and if I run `ls`, I see that the files in the directory bound from the host system are owned by root. The current user in the container matches the ownership of the files and the example works. If I create a file in the bound directory, e.g. `touch test.txt`, I see that the file is owned by root, but when I exit the container, the file I created is owned by my user on the host system. There is a simple mapping between my user on the host system and root within the container.

On Linux, this mapping is not happening by default (maybe there's a simple setting to enable this?) (`Docker 20.10.5`). I unzip the `gh-pages.zip` file on the host system and it's owned by my user. I then enter the container where I'm now `root` but the files in the bound directory show ownership as the UID/GID of my user on the host system. The name doesn't show because the user/group aren't present in `/etc/passwd` and `/etc/group` in the container. Attempting to run `jekyll serve` fails. If I start the container using the `-U` switch and specifying my UID/GID, things get further but fail on the dependency installation because I'm no longer `root` in the container and it's trying to install dependencies into a root-owned location!

I assume there's a straightforward fix to this...
